Add rgb function
sixtyfpsui/sixtyfps pull request #139
Opened 2020-12-30 16:50 UTC by sanxiyn

2020-12-30 17:50 UTC, ogoffart requested changes
Thanks for the contribution!

Just some minor requests:
 - Add the C++ variant
 - Add license header
 - There should be a test. I recommand adding a fiew colors in `tests/cases/types/color.60`

Please let me know if you can do these changes.  Otherwise i'll just merge as is and do the fixes myself.

2020-12-30 17:50 UTC, ogoffart commented on sixtyfps_compiler/generator/cpp.rs
> +            BuiltinFunction::Rgb => panic!(),
```suggestion
            BuiltinFunction::Rgb => "[](int r, int g, int b){ return sixtyfps::Color::from_rgb_uint8(std::clamp(r, 0, 255), std::clamp(g, 0, 255), std::clamp(b, 0, 255)); }".into(),
```

2020-12-30 17:50 UTC, ogoffart commented on examples/rgb_slider/build.rs
> +fn main() {
Every new rust / .60 files will need a copyright header (we have a test for that)

2020-12-30 17:59 UTC, ogoffart commented
Another point worth discuting: the CSS spec allow for both int between 0 and 255,  or a % value.
Maybe it is worth supporting something like `rgb(100%, 45%, 30%)`.  The problem is that our type system does not allow for overloads with different type yet.

2021-02-11 12:06 UTC, tronical commented
We would like to merge this and apply a few changes on top:

 * Support for percentage number literals
 * Add tests
 * Add C++ support

2021-04-12 13:19 UTC, closed without merging