sharedvector clear
sixtyfpsui/sixtyfps pull request #403
Opened 2021-08-11 17:10 UTC by tronical

2021-08-11 21:45 UTC, ogoffart requested changes
What's really the use case of going to great length to keep the capacity. In fact, you most likely want to clear just to say: "i want the vector to be empty now", so equivelent to `vec = SharedVector::default()`.
For comparison, that's what the QString::clear does (does not keep allocated memory).  QList::clear does what you do in Qt6, but it didn't do it always in Qt5.

Rust's `Vec::clear` or C++'s `std::vector::clear`  keeps the capacity, but that's easier to do in a non-shared vector.
I think i'd see a more usefull behavior as
 - keep the capacity if not shared
 - set to empty vector without capacity otherwise.

2021-08-11 21:45 UTC, ogoffart commented on sixtyfps_runtime/corelib/sharedvector.rs
> +        self.detach(self.capacity());
But detach will do a deep clone of everything inside, we don't want that when we want to clear. That's quite unintuitive.

2021-08-11 21:45 UTC, ogoffart commented on sixtyfps_runtime/corelib/sharedvector.rs
> +        // Safety: caller (and above debug_assert) must ensure that the array is not shared.
that should be an `assert`  or the function need to be marked `unsafe`

In fact, if it was public, i'd say that shrink should in fact detach if it is shared, but only clone new_len element to the final vector (and only allocates (new_len)

2021-08-12 06:34 UTC, tronical commented
> I think i'd see a more usefull behavior as
> 
> * keep the capacity if not shared
> * set to empty vector without capacity otherwise.

Sounds good to me.

2021-08-12 10:33 UTC, ogoffart approved these changes

2021-08-12 10:33 UTC, ogoffart commented on api/sixtyfps-cpp/include/sixtyfps_sharedvector.h
> +                it->~T();
(there is a leak when the destructor throws an exception, but let's ignore that :-)

2021-08-12 10:33 UTC, ogoffart commented on sixtyfps_runtime/corelib/sharedvector.rs
> +            self.inner = NonNull::from(&SHARED_NULL).cast();
```suggestion
            *self = SharedVector::default();
```

2021-08-12 11:41 UTC, merged