compilerlib: Fix an assert triggered by linear_gradient
sixtyfpsui/sixtyfps pull request #662
Opened 2021-11-20 14:57 UTC by hunger

Just remove the variant with the unserscore: Using it triggers an assert down
the line, so it does not seem to be used in the wild:-)

2021-11-20 15:04 UTC, hunger commented
If you want to be more careful and keep @linear_gradient supported, then I can also change the debug_asser_eq!(...).

2021-11-20 15:54 UTC, tronical commented
> If you want to be more careful and keep @linear_gradient supported, then I can also change the debug_asser_eq!(...).

That’s the syntax we permit for the image url, changing the debug assert seems consistent to me.

Perhaps along with test coverage in the syntax tests.

Just my two cents, I defer to @ogoffart for the final call :-)

2021-11-21 12:29 UTC, ogoffart requested changes
We claim in the documentation that foo_bar is the same as foo-bar, so we should accept `@linear_gradient`

2021-11-22 08:21 UTC, hunger commented
OK, I'll update the patch and remove or update the debug_assert instead.

2021-11-22 11:54 UTC, hunger commented
This time with both spellings intact and asserted for + a test for the alternate spelling of @image-url and @linear-gradient.

2021-11-22 12:21 UTC, ogoffart approved these changes

2021-11-22 12:21 UTC, merged