Add support for font-size to LineEdit and Text-Edit widgets.
sixtyfpsui/sixtyfps pull request #872
Opened 2022-01-24 18:01 UTC by besok

closes #435

2022-01-24 18:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sixtyfpsui/sixtyfps?pullRequest=872) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sixtyfpsui/sixtyfps?pullRequest=872) before we can accept your contribution.<br/><hr/>**zhguchev** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sixtyfpsui/sixtyfps?pullRequest=872) it.</sub>

2022-01-24 18:26 UTC, ogoffart commented
Thanks for the patch, the implementation looks good. but please clean it up a bit, don't modify the ignore file or the 7gui example. 
Appart from that, looks good to me

2022-01-24 18:45 UTC, ogoffart requested changes

2022-01-24 18:45 UTC, ogoffart commented on docs/widgets.md
> +    font-size: 14px;
That's in Window, not in the LineEdit

2022-01-24 21:17 UTC, besok commented on docs/widgets.md
> +    font-size: 14px;
right

2022-01-25 10:44 UTC, ogoffart commented
The commit of the pull request are not associated with your github account. Probably because the email doesn't match.
You need to make sure that the email that you used to make the commit is associated with your github account.  Or you can rebase and change the email in the commit to match the one associated with the github account.

2022-01-26 14:07 UTC, ogoffart approved these changes

2022-01-26 14:08 UTC, merged

2022-01-26 14:08 UTC, ogoffart commented
Thank you!